### ISSUE TITLE
Add custom CSS class

### ISSUE THREAD

**Issue by sbenilan** [taminomara/sphinx-a4doc#9]
Hi again,

sphinx-a4doc supports some default CSS class that I have found useful but limited. Would it be possible to add custom CSS support in g4 comment ? Maybe something like:

```
//@ doc:css_class <str>
g4rule : ... ;
````
That would help adding a bit of style (e.g. coloured DSL keyword) with autogrammar.

Thanks!

**Comment by AmatanHead** [comment]
So let me know if I understand you correctly, in your example above, you want any diagram that references `g4rule` to have `g4rule`s node to have a custom class?

This sounds interesting, I'll see if I can do it.

**Comment by sbenilan** [comment]
Exactly.

**Comment by taminomara** [comment]
It's been two years, I know... but, it's finally implemented.
